### ISSUE TITLE
debug smart contract

### ISSUE THREAD

**Issue by wisdomcsharp** [bitpopulous/populous-smartcontracts#126]
- [ ] - complete
debug smart contract code, and create a deposit address on the testnet

**Comment by najienka** [comment]
via Hubstaff
User: Nemitari Ajienka

Project: populous-smartcontracts - https://app.hubstaff.com/projects/354253
Date Range: 01/15/19 - 01/15/19
Work session total: 0:36:04

Grand total: 0:36:04

**Comment by najienka** [comment]
via Hubstaff
User: Nemitari Ajienka

Project: populous-smartcontracts - https://app.hubstaff.com/projects/354253
Date Range: 01/15/19 - 01/15/19
Work session total: 0:49:49

Grand total: 1:25:53

**Comment by najienka** [comment]
via Hubstaff
User: Nemitari Ajienka

Project: populous-smartcontracts - https://app.hubstaff.com/projects/354253
Date Range: 01/15/19 - 01/15/19
Work session total: 1:20:00

Grand total: 2:45:53

**Comment by najienka** [comment]
via Hubstaff
User: Nemitari Ajienka

Project: populous-smartcontracts - https://app.hubstaff.com/projects/354253
Date Range: 01/15/19 - 01/15/19
Work session total: 0:54:52

Grand total: 3:40:45
