### ISSUE TITLE
mint test PPT to main address

### ISSUE THREAD

**Issue by wisdomcsharp** [bitpopulous/populous-smartcontracts#129]
- [x] - complete

mint test PPT to: 0xf8b3d742b245ec366288160488a12e7a2f1d720d

**Comment by najienka** [comment]
truffle(ropsten)> ppt.balanceOf(web3.eth.coinbase).then(acctBalance => balance = acctBalance.toString(10))
'100000001300000000'

coinbase test PPT balance = 1 billion PPT @wisdomcsharp

**Comment by najienka** [comment]
via Hubstaff
User: Nemitari Ajienka

Project: populous-smartcontracts - https://app.hubstaff.com/projects/354253
Date Range: 01/17/19 - 01/17/19
Work session total: 0:33:44

Grand total: 0:33:44
